### ISSUE TITLE
Can't access instance attributes

### ISSUE THREAD

**Issue by AlexHill** [tbodt/v8py#16]
Hi,

Just clarifying what is and isn't possible with v8py - is it expected that instance attributes on objects exposed to V8 won't be accessible? e.g. attributes set in `__init__`? If so, is that a fundamental limitation or just a "not implemented yet"?

Many thanks,
Alex

**Comment by tbodt** [comment]
Yeah, that's intentional. The idea is to easily be able to make instance variables that are private to javascript, but public to python. `@property` works.

**Comment by AlexHill** [comment]
Gotcha, thanks. And from the look of the tests, `__getitem__` should work with dot notation in JS if I need to expose dynamic properties?

**Comment by tbodt** [comment]
Yep. JavaScript does not distinguish between . and [].

**Comment by AlexHill** [comment]
Ok. Thankyou!
