### ISSUE TITLE
Callback Function

### ISSUE THREAD

**Issue by LinkTed** [tbodt/v8py#30]
Hi,
how can I call a python function every time a javascript object is create or access (With the Debugger class)? I need this for analysis purpose.

Thanks for your attention.

**Comment by tbodt** [comment]
I don't believe the V8 debugger API supports that.

**Comment by LinkTed** [comment]
It do not have to be a callback or something like that and it do not have to be with the Debugger. Is there maybe a way like in the test_indexed_property.py (but it have to be for every object) to call a function when a object is create or acess?

**Comment by tbodt** [comment]
For *every* object? You could add hooks to the functions in pyclasshandlers.cpp.

**Comment by LinkTed** [comment]
Thanks for your answer but it works only for Python object (which are exposed) when i add hooks in py_class_construct_callback and py_class_method_callback. I need hooks for every object for example:
```javascript
// Hook for here
var s1 = new String();
// and here
var s2 = "Hello world!";
var r = s1.concat(s2);
```

Thanks for your help

**Comment by tbodt** [comment]
V8 doesn't support that. You could try and replace String with your own python class.
