### ISSUE TITLE
PyPI release for latest version

### ISSUE THREAD

**Issue by LincolnPuzey** [tbodt/v8py#34]
Hi,

Can we get a new release to PyPI for the latest version on github.

This is to take advantage of pip caching the wheels it builds from pypi dependencies, but not vcs dependencies.

Thanks!

**Comment by tbodt** [comment]
Just pushed and tagged a release commit, if I did everything right travis should automatically make a pypi release.

**Comment by LincolnPuzey** [comment]
Awesome thanks I can see it on pypi.
