### ISSUE TITLE
Can I render PDF from HTML by using this library?

### ISSUE THREAD

**Issue by Spawn** [tbodt/v8py#37]

**Comment by tbodt** [comment]
No

**Comment by tbodt** [comment]
This is just a library for running JavaScript. You're probably looking for something like wkhtmltopdf or headless chrome.

**Comment by Spawn** [comment]
Unfortunately I want to use python wrapper to render html from pdf fast. wkhtmltopdf is working not correctly (sometimes doesn't load images by links) and headless chrome accepts data through socket and It makes impossible to figure out *when* pdf is rendered. I need some python wrapper for some of browser engines or low-level libraries for pdf rendering. But thank you for answer :slightly_smiling_face:

**Comment by tbodt** [comment]
With a bit of work you can probably do what you need by rewriting https://github.com/spajak/cef-pdf in python.

**Comment by Spawn** [comment]
Will check, thanks!
