### ISSUE TITLE
stuck at "Running setup.py install for v8py" for literally hours

### ISSUE THREAD

**Issue by cg-cnu** [tbodt/v8py#4]
Thanks for the heads up in readme! But, is it possible to use the existing v8 engine installed on the system? Super excited to get this working. Now, waiting for my setup to complete :)

**Comment by tbodt** [comment]
Unfortunately, no, as v8py statically links with a version of v8 built with special flags. See setup.py for details. You can use `pip install -v v8py` to see the output of the v8 building process, though.

**Comment by cg-cnu** [comment]
Hey sorry for getting back late,

I ran ```sudo pip install v8py```
The kept for overnight pip install and it failed with this error. 
```
      LINK(target) /tmp/pip-build-Dc1ECn/v8py/v8/out/native/v8_simple_wasm_types_section_fuzzer
      LINK(target) /tmp/pip-build-Dc1ECn/v8py/v8/out/native/unittests
      TOUCH /tmp/pip-build-Dc1ECn/v8py/v8/out/native/obj.target/gypfiles/All.stamp
    rm src_inspector_inspector_gyp_protocol_generated_sources_target_protocol_generated_sources.intermediate
    make[1]: Leaving directory `/tmp/pip-build-Dc1ECn/v8py/v8/out'
    error: /tmp/pip-build-Dc1ECn/include: No such file or directory

    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-Dc1ECn/v8py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-7mehsC-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-Dc1ECn/v8py/

```
Am not exactly sure of the issue. I am going to try one more time and see if there is anything issue with my environment and gonna monitor it this time.

**Comment by tbodt** [comment]
I'll look into the error. I have a funny feeling it would work in a virtualenv, so could you try that?

**Comment by tbodt** [comment]
Actually I'm pretty sure I know what the problem is. `pip install greenstack` before installing v8py should fix it. Let me know if it does. (You can uninstall greenstack after installing v8py if you like.)

**Comment by cg-cnu** [comment]
installing greenstack fixed the issue. Thanks!
