### ISSUE TITLE
add progress bar?!

### ISSUE THREAD

**Issue by seighail3** [tbodt/v8py#42]
![image](https://user-images.githubusercontent.com/70487576/93204707-3583b800-f75f-11ea-8337-6c6c918824ae.png)

Also add binaries for windows 
thanks :D

**Comment by tbodt** [comment]
pip doesn't have any way to display any output during this step, unless you use --verbose.

I don't use windows, perhaps someone can volunteer to add CI.

**Comment by desertkun** [comment]
I have uploaded prebuilt images on my [fork](https://github.com/anthill-utils/v8py), windows included:
```bash
pip install -i https://cdn.anthillplatform.org/python v8py
```

The builds are a bit old, though.
